// <auto-generated />
using System;
using GalleryCloud.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalleryCloud.Api.Data.Migrations.ThumbnailDb
{
    [DbContext(typeof(ThumbnailDbContext))]
    partial class ThumbnailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GalleryCloud.Core.Entities.ThumbnailCache", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("PhotoId", "Size");

                    b.ToTable("ThumbnailCache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
