// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GalleryCloud.Api.Data
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fa30c00a-6059-446d-b2da-2f81e54462a2"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var favorite = FavoriteEntityType.Create(this);
            var photo = PhotoEntityType.Create(this);
            var photoTag = PhotoTagEntityType.Create(this);
            var scanLog = ScanLogEntityType.Create(this);
            var systemSetting = SystemSettingEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var user = UserEntityType.Create(this);

            FavoriteEntityType.CreateForeignKey1(favorite, photo);
            FavoriteEntityType.CreateForeignKey2(favorite, user);
            PhotoEntityType.CreateForeignKey1(photo, user);
            PhotoTagEntityType.CreateForeignKey1(photoTag, photo);
            PhotoTagEntityType.CreateForeignKey2(photoTag, tag);
            ScanLogEntityType.CreateForeignKey1(scanLog, user);
            TagEntityType.CreateForeignKey1(tag, user);

            FavoriteEntityType.CreateAnnotations(favorite);
            PhotoEntityType.CreateAnnotations(photo);
            PhotoTagEntityType.CreateAnnotations(photoTag);
            ScanLogEntityType.CreateAnnotations(scanLog);
            SystemSettingEntityType.CreateAnnotations(systemSetting);
            TagEntityType.CreateAnnotations(tag);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
