// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GalleryCloud.Api.Data
{
    public partial class ThumbnailDbContextModel
    {
        private ThumbnailDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e13ed23e-6479-40a7-836e-0f8ea4f403ae"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var thumbnailCache = ThumbnailCacheEntityType.Create(this);

            ThumbnailCacheEntityType.CreateAnnotations(thumbnailCache);

            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
