// <auto-generated />
using GalleryCloud.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ThumbnailDbContext), typeof(ThumbnailDbContextModel))]
